@startuml

package "Naviguateur" {
  [Map de Nancy]
}

database "Database" {
  [Restaurants]
  [Reservations]
}

cloud "APIs JS" {
  [Weather]
  [Velib Stations]
}

cloud "APIs" {
  [Traffic Incident]
  [Etablissements Supérieurs]
}

node "Services RMI" {
  [m1]
  [m2]
  [m3]
}

"Naviguateur" --> m3 : HTTP Requests
"Naviguateur" --> "APIs JS" : fetch
m3 --> m2 : RMI Requests
m2 --> APIs : API Requests
m1 --> Database : JDBC Connection
m3 --> m1 : RMI Requests

@enduml